# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OSCAL
email: oscal@nist.gov
description: >- # this means to ignore newlines until "baseurl:"
  OSCAL - more insight, less paper
baseurl: "/OSCAL" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: content/documentation/schemas/

collections:
  oscal-catalog-xml:
    title: Catalog XML
  oscal-catalog-json:
    title: Catalog JSON
  oscal-profile-xml:
    title: Profile XML
  oscal-profile-json:
    title: Profile JSON
  oscal-component-xml:
    title: Component XML
  oscal-component-json:
    title: Component JSON

markdown: kramdown
highlighter: rouge

site_width: wide

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: uswds-jekyll
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile
  - Dockerfile.dev
  - package.json
  - package-lock.json
  - README.md
# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: oscal

google_analytics_ua: UA-42404149-54

search: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
